# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QA_GM_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from MyPoco.my_poco import MyPoco
from PyQt5 import QtCore, QtGui, QtWidgets
import time, os, ast
from PyQt5.QtCore import QDir


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.my_poco = None
        Dialog.setObjectName("Dialog")
        Dialog.resize(905, 735)
        self.new_account_box = QtWidgets.QGroupBox(Dialog)
        self.new_account_box.setGeometry(QtCore.QRect(9, 9, 891, 191))
        self.new_account_box.setObjectName("new_account_box")
        self.game_name = QtWidgets.QComboBox(self.new_account_box)
        self.game_name.setGeometry(QtCore.QRect(10, 40, 121, 31))
        self.game_name.setObjectName("game_name")
        self.game_name.addItem('请选择游戏版本')
        self.game_name.addItem('少三2')
        self.game_name.addItem('少三2台湾')
        self.game_name.addItem('少三2日本')
        self.game_name.addItem('少三2新马')
        self.game_name.addItem('少三2韩国')
        self.sever_name = QtWidgets.QComboBox(self.new_account_box)
        self.sever_name.setGeometry(QtCore.QRect(140, 40, 111, 31))
        self.sever_name.setObjectName("sever_name")
        self.sever_name.addItem('请选择区服')
        self.sever_name.addItem('QA1')
        self.sever_name.addItem('QA2')
        self.sever_name.addItem('QA3')
        self.sever_name.addItem('QA4')
        self.sever_name.addItem('QA5')
        self.sever_name.addItem('QA6')
        self.sever_name.addItem('QA7')
        self.sever_name.addItem('QA8')
        self.sever_name.addItem('新QA1')
        self.sever_name.addItem('新QA2')
        self.sever_name.addItem('新QA3')
        self.sever_name.addItem('新QA4')
        self.sever_name.addItem('新QA5')
        self.is_Random_account = QtWidgets.QRadioButton(self.new_account_box)
        self.is_Random_account.setGeometry(QtCore.QRect(400, 50, 91, 21))
        self.is_Random_account.setObjectName("is_Random_account")
        self.input_account = QtWidgets.QLineEdit(self.new_account_box)
        self.input_account.setGeometry(QtCore.QRect(260, 40, 131, 31))
        self.input_account.setClearButtonEnabled(True)
        self.input_account.setObjectName("input_account")
        self.Resources_input_text = QtWidgets.QTextEdit(self.new_account_box)
        self.Resources_input_text.setGeometry(QtCore.QRect(10, 140, 871, 41))
        self.Resources_input_text.setObjectName("Resources_input_text")
        self.new_login_account = QtWidgets.QPushButton(self.new_account_box)
        self.new_login_account.setGeometry(QtCore.QRect(790, 70, 91, 61))
        self.new_login_account.setObjectName("new_login_account")
        self.juntuan_name = QtWidgets.QLineEdit(self.new_account_box)
        self.juntuan_name.setGeometry(QtCore.QRect(20, 90, 71, 31))
        self.juntuan_name.setObjectName("juntuan_name")
        self.juntuan_level = QtWidgets.QLineEdit(self.new_account_box)
        self.juntuan_level.setGeometry(QtCore.QRect(110, 90, 71, 31))
        self.juntuan_level.setObjectName("juntuan_level")
        self.new_join_guild = QtWidgets.QCheckBox(self.new_account_box)
        self.new_join_guild.setGeometry(QtCore.QRect(200, 90, 101, 21))
        self.new_join_guild.setObjectName("new_join_guild")
        self.account_tips = QtWidgets.QLabel(self.new_account_box)
        self.account_tips.setGeometry(QtCore.QRect(10, 5, 281, 31))
        self.account_tips.setObjectName("account_tips")
        self.fuben_num = QtWidgets.QTextEdit(self.new_account_box)
        self.fuben_num.setGeometry(QtCore.QRect(500, 50, 71, 31))
        self.fuben_num.setObjectName("fuben_num")
        self.yijian_zhuangbei = QtWidgets.QCheckBox(self.new_account_box)
        self.yijian_zhuangbei.setGeometry(QtCore.QRect(400, 20, 91, 21))
        self.yijian_zhuangbei.setObjectName("yijian_zhuangbei")
        self.jingyanshuxing = QtWidgets.QCheckBox(self.new_account_box)
        self.jingyanshuxing.setGeometry(QtCore.QRect(580, 20, 161, 21))
        self.jingyanshuxing.setChecked(True)
        self.jingyanshuxing.setObjectName("jingyanshuxing")
        self.haoyou_num_2 = QtWidgets.QLineEdit(self.new_account_box)
        self.haoyou_num_2.setGeometry(QtCore.QRect(500, 10, 71, 31))
        self.haoyou_num_2.setClearButtonEnabled(True)
        self.haoyou_num_2.setObjectName("haoyou_num_2")
        self.clear_resource = QtWidgets.QPushButton(self.new_account_box)
        self.clear_resource.setGeometry(QtCore.QRect(820, 30, 61, 31))
        self.clear_resource.setObjectName("clear_resource")
        self.activities_box = QtWidgets.QGroupBox(Dialog)
        self.activities_box.setGeometry(QtCore.QRect(10, 200, 891, 331))
        self.activities_box.setObjectName("activities_box")
        self.activities_list = QtWidgets.QToolBox(self.activities_box)
        self.activities_list.setGeometry(QtCore.QRect(10, 10, 851, 311))
        self.activities_list.setObjectName("activities_list")
        self.haoling = QtWidgets.QWidget()
        self.haoling.setGeometry(QtCore.QRect(0, 0, 851, 215))
        self.haoling.setObjectName("haoling")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.haoling)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(160, 100, 591, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.haoling1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.haoling1.setObjectName("haoling1")
        self.horizontalLayout_9.addWidget(self.haoling1)
        self.haoling2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.haoling2.setObjectName("haoling2")
        self.horizontalLayout_9.addWidget(self.haoling2)
        self.haoling3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.haoling3.setObjectName("haoling3")
        self.haoling3.setText("True/False")
        self.horizontalLayout_9.addWidget(self.haoling3)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.haoling)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(160, 60, 591, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.haolingt1 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.haolingt1.setObjectName("haolingt1")
        self.horizontalLayout_10.addWidget(self.haolingt1)
        self.haolingt2 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.haolingt2.setObjectName("haolingt2")
        self.horizontalLayout_10.addWidget(self.haolingt2)
        self.haolingt3 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.haolingt3.setObjectName("haolingt3")
        self.horizontalLayout_10.addWidget(self.haolingt3)
        self.haolingkaishi = QtWidgets.QPushButton(self.haoling)
        self.haolingkaishi.setGeometry(QtCore.QRect(50, 70, 71, 51))
        self.haolingkaishi.setObjectName("haolingkaishi")
        self.activities_list.addItem(self.haoling, "")
        self.fujia = QtWidgets.QWidget()
        self.fujia.setGeometry(QtCore.QRect(0, 0, 851, 215))
        self.fujia.setObjectName("fujia")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.fujia)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(170, 110, 591, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fujia1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.fujia1.setObjectName("fujia1")
        self.horizontalLayout_7.addWidget(self.fujia1)
        self.fujia2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.fujia2.setObjectName("fujia2")
        self.horizontalLayout_7.addWidget(self.fujia2)
        self.fujia3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.fujia3.setObjectName("fujia3")
        self.horizontalLayout_7.addWidget(self.fujia3)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.fujia)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(170, 70, 591, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fujiat1 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.fujiat1.setObjectName("fujiat1")
        self.horizontalLayout_8.addWidget(self.fujiat1)
        self.fujiat2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.fujiat2.setObjectName("fujiat2")
        self.horizontalLayout_8.addWidget(self.fujiat2)
        self.fujiat3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.fujiat3.setObjectName("fujiat3")
        self.horizontalLayout_8.addWidget(self.fujiat3)
        self.fujiakaishi = QtWidgets.QPushButton(self.fujia)
        self.fujiakaishi.setGeometry(QtCore.QRect(60, 80, 71, 51))
        self.fujiakaishi.setObjectName("fujiakaishi")
        self.activities_list.addItem(self.fujia, "")
        self.huashen = QtWidgets.QWidget()
        self.huashen.setObjectName("huashen")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.huashen)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(170, 100, 591, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.huashen1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.huashen1.setObjectName("huashen1")
        self.horizontalLayout_5.addWidget(self.huashen1)
        # self.huashen2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        # self.huashen2.setObjectName("huashen2")
        # self.horizontalLayout_5.addWidget(self.huashen2)
        # self.huashen3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        # self.huashen3.setObjectName("huashen3")
        # self.horizontalLayout_5.addWidget(self.huashen3)
        self.huashen4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.huashen4.setObjectName("huashen4")
        self.horizontalLayout_5.addWidget(self.huashen4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.huashen)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(170, 60, 591, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.huashent1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.huashent1.setObjectName("huashent1")
        self.horizontalLayout_6.addWidget(self.huashent1)
        # self.huashent2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        # self.huashent2.setObjectName("huashent2")
        # self.horizontalLayout_6.addWidget(self.huashent2)
        # self.huashent3 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        # self.huashent3.setObjectName("huashent3")
        # self.horizontalLayout_6.addWidget(self.huashent3)
        self.huashent4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.huashent4.setObjectName("huashent4")
        self.horizontalLayout_6.addWidget(self.huashent4)
        self.huashenkaishi = QtWidgets.QPushButton(self.huashen)
        self.huashenkaishi.setGeometry(QtCore.QRect(60, 70, 71, 51))
        self.huashenkaishi.setObjectName("huashenkaishi")
        self.activities_list.addItem(self.huashen, "")
        self.hengsaoqianjun = QtWidgets.QWidget()
        self.hengsaoqianjun.setObjectName("hengsaoqianjun")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.hengsaoqianjun)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 80, 591, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hengsao1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.hengsao1.setObjectName("hengsao1")
        self.horizontalLayout.addWidget(self.hengsao1)
        # self.hengsao2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        # self.hengsao2.setObjectName("hengsao2")
        # self.horizontalLayout.addWidget(self.hengsao2)
        # self.hengsao3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        # self.hengsao3.setObjectName("hengsao3")
        # self.horizontalLayout.addWidget(self.hengsao3)
        self.hengsao4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.hengsao4.setObjectName("hengsao4")
        self.horizontalLayout.addWidget(self.hengsao4)
        self.hengsaokaishi = QtWidgets.QPushButton(self.hengsaoqianjun)
        self.hengsaokaishi.setGeometry(QtCore.QRect(40, 50, 71, 51))
        self.hengsaokaishi.setObjectName("hengsaokaishi")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.hengsaoqianjun)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 40, 591, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hengsaot1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.hengsaot1.setObjectName("hengsaot1")
        self.horizontalLayout_2.addWidget(self.hengsaot1)
        # self.hengsaot2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        # self.hengsaot2.setObjectName("hengsaot2")
        # self.horizontalLayout_2.addWidget(self.hengsaot2)
        # self.hengsaot3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        # self.hengsaot3.setObjectName("hengsaot3")
        # self.horizontalLayout_2.addWidget(self.hengsaot3)
        self.hengsaot4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.hengsaot4.setObjectName("hengsaot4")
        self.horizontalLayout_2.addWidget(self.hengsaot4)
        self.activities_list.addItem(self.hengsaoqianjun, "")
        self.xianshijinjiang = QtWidgets.QWidget()
        self.xianshijinjiang.setObjectName("xianshijinjiang")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.xianshijinjiang)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(170, 100, 661, 31))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.xianshijinjiang1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.xianshijinjiang1.setObjectName("xianshijinjiang1")
        self.horizontalLayout_11.addWidget(self.xianshijinjiang1)
        self.xianshijinjiang2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.xianshijinjiang2.setObjectName("xianshijinjiang2")
        self.horizontalLayout_11.addWidget(self.xianshijinjiang2)
        self.xianshijinjiang3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.xianshijinjiang3.setObjectName("xianshijinjiang3")
        self.horizontalLayout_11.addWidget(self.xianshijinjiang3)
        # self.xianshijinjiang4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        # self.xianshijinjiang4.setObjectName("xianshijinjiang4")
        # self.horizontalLayout_11.addWidget(self.xianshijinjiang4)
        self.xianshijinjiang5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.xianshijinjiang5.setObjectName("xianshijinjiang5")
        self.horizontalLayout_11.addWidget(self.xianshijinjiang5)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.xianshijinjiang)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(170, 60, 661, 31))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.xianshijinjiangt1 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.xianshijinjiangt1.setObjectName("xianshijinjiangt1")
        self.horizontalLayout_12.addWidget(self.xianshijinjiangt1)
        self.xianshijinjiangt2 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.xianshijinjiangt2.setObjectName("xianshijinjiangt2")
        self.horizontalLayout_12.addWidget(self.xianshijinjiangt2)
        self.xianshijinjiangt3 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.xianshijinjiangt3.setObjectName("xianshijinjiangt3")
        self.horizontalLayout_12.addWidget(self.xianshijinjiangt3)
        # self.xianshijinjiangt4 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        # self.xianshijinjiangt4.setObjectName("xianshijinjiangt4")
        # self.horizontalLayout_12.addWidget(self.xianshijinjiangt4)
        self.xianshijinjiangt5 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.xianshijinjiangt5.setObjectName("xianshijinjiangt5")
        self.horizontalLayout_12.addWidget(self.xianshijinjiangt5)
        self.xianshijinjiangkaishi = QtWidgets.QPushButton(self.xianshijinjiang)
        self.xianshijinjiangkaishi.setGeometry(QtCore.QRect(60, 70, 71, 51))
        self.xianshijinjiangkaishi.setObjectName("xianshijinjiangkaishi")
        self.activities_list.addItem(self.xianshijinjiang, "")
        self.quesheng = QtWidgets.QWidget()
        self.quesheng.setObjectName("quesheng")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.quesheng)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(180, 90, 591, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_3.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_3.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_3.addWidget(self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_3.addWidget(self.lineEdit_33)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.quesheng)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(180, 50, 591, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.pushButton_13 = QtWidgets.QPushButton(self.quesheng)
        self.pushButton_13.setGeometry(QtCore.QRect(70, 60, 71, 51))
        self.pushButton_13.setObjectName("pushButton_13")
        self.activities_list.addItem(self.quesheng, "")
        self.log_Box = QtWidgets.QGroupBox(Dialog)
        self.log_Box.setGeometry(QtCore.QRect(10, 530, 891, 201))
        self.log_Box.setObjectName("log_Box")
        self.log_show_text = QtWidgets.QTextBrowser(self.log_Box)
        self.log_show_text.setGeometry(QtCore.QRect(10, 50, 871, 141))
        self.log_show_text.setObjectName("log_show_text")
        self.log_tips = QtWidgets.QLabel(self.log_Box)
        self.log_tips.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.log_tips.setObjectName("log_tips")
        self.clear_log = QtWidgets.QPushButton(self.log_Box)
        self.clear_log.setGeometry(QtCore.QRect(794, 12, 91, 31))
        self.clear_log.setObjectName("clear_log")

        self.retranslateUi(Dialog)
        self.activities_list.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.show()

    def add_resource(self, name, num):
        """
        添加道具，使用协议，不区分地区
        :param name: 道具名字
        :param num: 添加数量
        :return:
        """
        add_type, add_value = self.my_poco.protocol.mri.get_type_id_from_name(name)
        self.my_poco.protocol.add_resource_pb(add_type, add_value, num)

    def del_resource(self):
        """
        删除道具，使用协议，不区分地区
        :param name: 道具名字
        :param num: 添加数量
        :return:
        """
        print("******************")
        if self.my_poco !=None:
            print("******************")
            self.my_poco.del_all_resource_pb()
            # 删除道具
            add_type, add_value = self.my_poco.protocol.mri.get_type_id_from_name("元宝")
            yuanbaoshuliang = self.my_poco.protocol.get_resource_pb_yuanbao()
            self.my_poco.protocol.del_resource_pb(add_type, add_value, yuanbaoshuliang)
            self.add_log("账号：" + self.account + "资源清除完毕")
        else:
            print("********-----------**********")
            self.add_log("请先登录")

    def add_log(self, str_into):
        """
        显示日志
        :param str_into:
        :return:
        """
        new_log = self.log_show_text.toPlainText()
        set_log = new_log + "\r\n" + str_into
        self.log_show_text.setText(set_log)

    def clear_log_text(self):
        """
        显示日志
        :param str_into:
        :return:
        """
        self.log_show_text.setText("")

    def haoling_def(self):
        name = self.haoling1.text()
        num = self.haoling2.text()
        is_join = self.haoling3.text()
        if is_join == "True":
            is_join = True
        elif is_join == "":
            is_join = ""
        else:
            is_join = False
        if self.my_poco != None:
            try:
                self.my_poco.GM_fengkuang_haoling(name, int(num), join=is_join)
            except Exception:
                self.add_log("活动进行失败，想知道失败原因，坐等后续优化.....")
                return ""
        else:
            self.add_log("请先登录")
            return ""
        self.add_log("旗子捐献成功")

    def hengsaoqianjun_def(self):
        id = self.hengsao1.text()
        # name = self.hengsao2.text()
        # num = self.hengsao3.text()
        cishu = self.hengsao4.text()
        if self.my_poco != None:
            try:
                log_str_z, tongji_str_z, shijiancishu  = self.my_poco.GM_fengkuang_hengsaoqianjun(int(id),int(cishu))
            except Exception:
                self.add_log("活动进行失败，想知道失败原因，坐等后续优化.....")
                return ""
        else:
            self.add_log("请先登录")
            return ""
        self.add_log("总计获得：")
        self.add_log(log_str_z)
        self.add_log(tongji_str_z)


    def huashen_def(self):
        id = self.huashen1.text()
        # name = self.huashen2.text()
        # num = self.huashen3.text()
        cishu = self.huashen4.text()
        if self.my_poco != None:
            try:
                log_str_z, tongji_str_z, shijiancishu = self.my_poco.GM_fengkuang_huashen(int(id), int(cishu))
            except Exception:
                self.add_log("活动进行失败，想知道失败原因，坐等后续优化.....")
                return ""
        else:
            self.add_log("请先登录")
            return ""
        self.add_log("总计获得：")
        self.add_log(log_str_z)
        self.add_log(tongji_str_z)

    def xianshijinjiang_def(self):
        id = self.xianshijinjiang1.text()
        huodong_name = self.xianshijinjiang2.text()
        zhenying = self.xianshijinjiang3.text()
        # resource_name = self.xianshijinjiang4.text()
        cishu = self.xianshijinjiang5.text()
        if self.my_poco != None:
            try:
                log_str_z, tongji_str_z, shijiancishu  = self.my_poco.GM_fengkuang_xianshijinjiang(int(id), huodong_name, zhenying,
                                                                int(cishu))
            except Exception:
                self.add_log("活动进行失败，想知道失败原因，坐等后续优化.....")
                return ""
        else:
            self.add_log("请先登录")
            return ""
        self.add_log("总计获得：")
        self.add_log(log_str_z)
        self.add_log(tongji_str_z)

    def fujiatianxia_def(self):
        id = self.fujia1.text()
        sub_type = self.fujia2.text()
        cishu = self.fujia3.text()
        if self.my_poco != None:
            try:
                log_str_z, tongji_str_z, shijiancishu = self.my_poco.GM_fengkuang_fujia(int(id), int(sub_type),
                                                                                        int(cishu))
            except Exception:
                self.add_log("活动进行失败，想知道失败原因，坐等后续优化.....")
                return ""
        else:
            self.add_log("请先登录")
            return ""
        self.add_log("总计获得：")
        self.add_log(log_str_z)
        self.add_log(tongji_str_z)
        self.add_log(shijiancishu)

    def win_clicked(self):
        """
        绑定事件
        :return:
        """
        self.clear_log.clicked.connect(self.clear_log_text)
        self.new_login_account.clicked.connect(self.new_account)
        self.clear_resource.clicked.connect(self.del_resource)
        self.huashenkaishi.clicked.connect(self.huashen_def)
        self.hengsaokaishi.clicked.connect(self.hengsaoqianjun_def)
        self.haolingkaishi.clicked.connect(self.haoling_def)
        self.xianshijinjiangkaishi.clicked.connect(self.xianshijinjiang_def)
        self.fujiakaishi.clicked.connect(self.fujiatianxia_def)

    def new_account(self):
        exe_path = QDir.currentPath()
        exe_path = os.path.abspath(exe_path + "/MyPoco")
        game_name = self.game_name.currentText()  # 获取游戏名称
        if "请选择游戏版本" == game_name:
            self.add_log("请选择游戏版本")
            return ""
        sever_name = self.sever_name.currentText()  # 获取游戏区服
        if sever_name == "请选择区服":
            self.add_log("请选择服务器")
            return ""
        self.my_poco = MyPoco(game_name, None, ui_path=exe_path)
        if self.is_Random_account.isChecked():  # 是否随机账号
            account = self.my_poco.get_random_account()
        else:
            account = self.input_account.text()
            if account == "":
                self.add_log("请输入账号")
                return ""
        self.add_log("当前正在创建的账号为：" + account)
        try:
            self.my_poco.make_new_role(sever_name,account)
            if self.jingyanshuxing.isChecked():
                self.add_resource("角色经验", 99999999)
                self.add_log("经验添加完毕")
                self.add_resource("测试属性", 99999999)
                self.add_log("测试属性添加完毕")
        except Exception:
            self.add_log("创建失败")
            return ""
        self.account = account
        resource_dic_str = self.Resources_input_text.toPlainText()
        if "请输入需要的资源" not in resource_dic_str:
            resource_dic = ast.literal_eval(resource_dic_str)
            for key in resource_dic.keys():
                self.add_resource(key, int(resource_dic[key]))
            self.add_log("道具" + resource_dic_str + "添加成功")
        fuben_num = self.fuben_num.toPlainText()
        if fuben_num =="0":
            pass
        elif fuben_num!="":
            role_id, sever_time = self.my_poco.protocol.get_role_id()
            self.my_poco.set_account_information_gm(account, sever_name, role_id)
            fuben_str = "副本-" + fuben_num
            self.my_poco.set_checkpoint(account, sever_name, {"副本": fuben_str})
            self.add_log("副本进度设置完毕")
        else:
            self.add_log("请设置副本通关进度")
            return ""
        if self.yijian_zhuangbei.isChecked():
            try:
                self.my_poco.GM_yijian_chuanzhuangbei()
            except Exception:
                self.add_log("穿戴装备失败")
                return ""
        haoyou_num = self.haoyou_num_2.text()
        if haoyou_num != "":
            try:
                self.my_poco.GM_fengkuang_haoyou(int(haoyou_num), self.account, sever_name)
                self.add_log(haoyou_num+"个好友添加成功")
            except Exception:
                self.add_log("好友添加失败")
                return ""
        juntuan_name = self.juntuan_name.text()
        juntuan_level_str = self.juntuan_level.text()
        if self.jingyanshuxing.isChecked():
            is_join = True
        else:
            is_join =False
        if juntuan_name != "" and juntuan_level_str != "":
            try:
                juntuan_level = int(juntuan_level_str)
            except Exception:
                self.add_log("请输入数字")
                return ""
            try:
                self.my_poco.GM_new_join_guild(juntuan_name,juntuan_level,is_join)
                self.add_log(str(juntuan_level)+"级军团等级设置成功")
            except Exception:
                self.add_log("军团等级设置失败")
                return ""
        log_text = "角色创建完毕，账号为:" + account + ",在" + game_name + "-" + sever_name + "服"
        self.add_log(log_text)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.new_account_box.setTitle(_translate("Dialog", "GroupBox"))
        self.is_Random_account.setText(_translate("Dialog", "是否随机账号"))
        self.input_account.setPlaceholderText(_translate("Dialog", "请输入账号"))
        # self.Resources_input_text.setPlaceholderText(_translate("Dialog", "请输入需要的资源"))
        self.Resources_input_text.setText('''请输入需要的资源，格式："":,{"元宝":99999,}''')
        self.new_login_account.setText(_translate("Dialog", "登录/创建账号"))
        self.account_tips.setText(_translate("Dialog", "需要先创建/登录账号才可进行后续操作"))
        self.fuben_num.setPlaceholderText(_translate("Dialog", "副本通关数"))
        self.yijian_zhuangbei.setText(_translate("Dialog", "是否穿戴装备"))
        self.jingyanshuxing.setText(_translate("Dialog", "是否添加经验和测试属性"))
        self.haoyou_num_2.setPlaceholderText(_translate("Dialog", "添加好友数"))
        self.juntuan_name.setPlaceholderText(_translate("Dialog", "军团名称"))
        self.juntuan_level.setPlaceholderText(_translate("Dialog", "军团等级"))
        self.new_join_guild.setText(_translate("Dialog", "加入/创建军团"))
        self.clear_resource.setText(_translate("Dialog", "清空资源"))
        self.activities_box.setTitle(_translate("Dialog", "GroupBox"))
        self.haolingt1.setText(_translate("Dialog", "军团名"))
        self.haolingt2.setText(_translate("Dialog", "旗子捐献数量"))
        self.haolingt3.setText(_translate("Dialog", "加入/创建军团"))
        self.haolingkaishi.setText(_translate("Dialog", "开始"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.haoling), _translate("Dialog", "号令天下"))
        self.fujiat1.setText(_translate("Dialog", "活动ID"))
        self.fujiat2.setText(_translate("Dialog", "1金/2紫金"))
        self.fujiat3.setText(_translate("Dialog", "抽取次数"))
        self.fujiakaishi.setText(_translate("Dialog", "开始"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.fujia), _translate("Dialog", "富甲天下"))
        self.huashent1.setText(_translate("Dialog", "活动ID"))
        # self.huashent2.setText(_translate("Dialog", "道具名（元宝）"))
        # self.huashent3.setText(_translate("Dialog", "道具数量（6666个）"))
        self.huashent4.setText(_translate("Dialog", "抽取次数"))
        self.huashenkaishi.setText(_translate("Dialog", "开始"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.huashen), _translate("Dialog", "化身"))
        self.hengsaokaishi.setText(_translate("Dialog", "开始"))
        self.hengsaot1.setText(_translate("Dialog", "活动ID"))
        # self.hengsaot2.setText(_translate("Dialog", "道具名字"))
        # self.hengsaot3.setText(_translate("Dialog", "道具数量"))
        self.hengsaot4.setText(_translate("Dialog", "抽取次数"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.hengsaoqianjun),
                                         _translate("Dialog", "横扫千军"))
        self.xianshijinjiang3.setPlaceholderText(_translate("Dialog", "魏/蜀/吴/群/金/紫金"))
        self.xianshijinjiangt1.setText(_translate("Dialog", "活动ID"))
        self.xianshijinjiangt2.setText(_translate("Dialog", "第几期活动的名字"))
        self.xianshijinjiangt3.setText(_translate("Dialog", "阵营"))
        # self.xianshijinjiangt4.setText(_translate("Dialog", "道具名字"))
        self.xianshijinjiangt5.setText(_translate("Dialog", "抽取次数"))
        self.xianshijinjiangkaishi.setText(_translate("Dialog", "开始"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.xianshijinjiang),
                                         _translate("Dialog", "限时金将"))
        self.label_6.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_13.setText(_translate("Dialog", "开始"))
        self.activities_list.setItemText(self.activities_list.indexOf(self.quesheng), _translate("Dialog", "缺省"))
        self.log_Box.setTitle(_translate("Dialog", "GroupBox"))
        self.log_tips.setText(_translate("Dialog", "日志显示窗"))
        self.clear_log.setText(_translate("Dialog", "清空日志"))
        self.win_clicked()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    form = QtWidgets.QWidget()
    w = Ui_Dialog()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())
